### ISSUE TITLE
Violin, jitter, and boxplot don't align when using `color.by` in dittoPlot.

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/dittoSeq#100]
Reprex for dittoSeq v1.6.0:

```
library(recount3)
library(DESeq2)
library(SummarizedExperiment)

se <- recount3::create_rse_manual(
  project = "GBM",
  project_home = "data_sources/tcga",
  organism = "human",
  annotation = "gencode_v26",
  type = "gene"
)

assay(se, "counts") <- transform_counts(se)
assay(se, "raw_counts") <- NULL

rd <- rowData(se)
rownames(se) <- rd$gene_name

dds <- DESeqDataSet(se, design = ~tcga.gdc_cases.samples.sample_type)

assay(dds, "lognorm") <- assay(normTransform(dds))
assay(dds, "vst") <- assay(vst(dds))

dittoPlot(dds, "GFAP", group.by = "tcga.gdc_cases.samples.sample_type", 
  color.by = "tcga.gdc_cases.demographic.gender", assay = "vst", plots = c("vlnplot", "boxplot", "jitter"), 
  jitter.size = 1.5)
```
Results in:
![image](https://user-images.githubusercontent.com/10225716/145056978-b63898be-afa5-4eb9-8f49-8d43dd17fa6c.png)

I can't remember if we ran into this one previously or not. I'm not sure why the recurrent tumor group looks fine but the primaries don't.

**Comment by dtm2451** [comment]
Sorry for not responding to this one for so long!

We did address alignment of the representations a while back, but this hits an edge-case that wasn't addressed.  Specifically you have only one data point here for Primary Tumor - NA & that's enough to draw the jitter and boxplot representations, but not enough to calculate and draw the violin.  Thus your jitter and boxplots get spaced for 3 groups whereas the violin gets spaced for 2.  (Representation alignments look fine to me for Recurrent... & Solid..., just they get equal widths for their overall fewer groups).

You probably got a warning like this when the plot was made:
```
Warning messages:
1: Groups with fewer than two data points have been dropped.
```

I don't believe there is a way to make geom_violin still leave space for dropped groupings, so the only way to fix this misalignment would probably be to remove groups, with a warning, that have only 1 point.  That wouldn't fix the width differences between group.by's that have different numbers of color groups, but it would allow for all the data representations to vertically align!

**Comment by j-andrews7** [comment]
A good enough reason to me, closing this since it's a pretty rare case.
