### ISSUE TITLE
multi_dittoPlot() then ggsave() only writes out last plot

### ISSUE THREAD

**Issue by jdrnevich** [dtm2451/dittoSeq#103]
I just starting using multi_dittoPlot() and it is working very well. However, when I try to use ggsave() afterwards, only the last gene given is saved in the resulting .jpeg. Example code from the vignette:

```
multi_dittoPlot(sce, delta.genes[1:6], group.by = "label",
    vlnplot.lineweight = 0.2, jitter.size = 0.3)
ggsave("onlyCBLN4plot.jpeg")
```

However, the old-fashioned calling `jpeg()` then `dev.off()` does give me the plot I want:

```
jpeg("all6genesplot.jpeg", width = 7, height = 7, unit = "in", res = 300, quality = 100)
multi_dittoPlot(sce, delta.genes[1:6], group.by = "label",
    vlnplot.lineweight = 0.2, jitter.size = 0.3)
dev.off()
```

So there is a work around but it is cumbersome. Just wanted to point this out - hopefully there is a quick fix.

**Comment by dtm2451** [comment]
Hey there!  Sorry I took a while to get back to this!  I think this is a case of the default of ggsave's `plot` input being their `last_plot()` function.

It works for me if I pass the multi_dittoPlot call to ggsave directly, `ggsave("plot.jpeg", plot = multi_dittoPlot(...) )`.

I'm not sure if there is a last_plot() equivalent for grid.arrange outputs, but if there is, that's perhaps another method where you could output you plot first as above, then have the full item pulled in with `ggsave("plot.jpeg", plot = <last_grid()> )`

**Comment by dtm2451** [comment]
closing as I believe this is resolved, but feel free to reopen if not!
