### ISSUE TITLE
plotting multiple smoothers in the scatter plot

### ISSUE THREAD

**Issue by rahulnutron** [dtm2451/dittoSeq#107]
Dear dittoSeq team,

Thanks for this very useful package. 
I have a question regarding plotting smoothers in the scatter plot.

I used 

dittoScatterPlot(epi.integrated,x.var = "pseudotime",'AT1G61760') and got a plot

![image](https://user-images.githubusercontent.com/18325626/166025579-e8e06b4b-3f22-4365-9927-c0bde1308b2f.png)

This object (epi.integrated) is an integrated Seurat object of five samples. I want to get smoother like (see below) but for five different scatter smoothers for each sample. Something like plotSmoothers() of tradeSeq and group by "orig.ident" instead of lineages. Is it possible to obtain this directly from dittoScatterplot for model like "loess"?

![image](https://user-images.githubusercontent.com/18325626/166022446-8390dd7e-3cdd-46f8-b1fa-5f74f441b0ce.png)

Thanks,
Rahul

**Comment by dtm2451** [comment]
Hey Rahul!

I've not used tradeSeq to know exactly what the plotSmoothers() output is, but with a little ggplot coding, if you know the ggplot geom or stats you'd like to use, then you should be able to do this relatively easily!

You can have 'orig.ident' or any other gene/metadata pulled into the data.frame that's given to the top-level `ggplot(data=<data.frame>)`, at the start of dittoSeq's plot building, by using `extra.vars`!

Try:
```
# To see that data.frame
dittoScatterPlot(epi.integrated, x.var = "pseudotime", y.var='AT1G61760',
    data.out = TRUE)$Target_data

# I think this may be close to what you want?
dittoScatterPlot(epi.integrated, x.var = "pseudotime", y.var='AT1G61760',
    extra.vars = "orig.ident") +
    geom_smooth(
        mapping = aes(color = orig.ident),
        method = "loess",
        se = FALSE)
```

I describe the `extra.data` system as useful for making custom faceting in some of the documentation examples, but it's actually got lots of uses.  Like this one!

(See also `assay.extra`, `slot.extra`, and `adjustment.extra` inputs, if needed, for additional fine controls for the data extraction steps.)

**Comment by dtm2451** [comment]
Closing as it seems addressed, but feel free to open if not!
