### ISSUE TITLE
dittoHeatmap Error in .which_data(assay, slot, object)[genes, cells.use] :  invalid or not-yet-implemented 'Matrix' subsetting

### ISSUE THREAD

**Issue by pcantalupo** [dtm2451/dittoSeq#108]
Hello,

When running this
`dittoHeatmap(sce.symbol, genes = genes, annot.by = "label", cluster_rows = FALSE)`

I get the error:
```
Error in .which_data(assay, slot, object)[genes, cells.use] : 
  invalid or not-yet-implemented 'Matrix' subsetting
```

Here is a look at my objects:
```
> sce.symbol
class: SingleCellExperiment 
dim: 12212 1866 
metadata(1): Samples
assays(2): counts logcounts
rownames(12212): AL627309.1 RP11-206L10.9 ... AL354822.1 SRSF10
rowData names(6): ID Symbol ... discard hvgs
colnames: NULL
colData names(16): Sample Barcode ... label elbowlabel
reducedDimNames(4): PCA TSNE PCA.elbow TSNE.elbow
mainExpName: NULL
altExpNames(0):

> head(colData(sce.symbol),n=2)
DataFrame with 2 rows and 16 columns
                  Sample          Barcode       sum  detected subsets_Mito_sum subsets_Mito_detected
             <character>      <character> <numeric> <integer>        <numeric>             <integer>
1 ~/OneDrive - Univers.. AAACATACGGTACT-1      2400       637               78                    11
2 ~/OneDrive - Univers.. AAACATTGCTCGCT-1      1374       428               47                     9
  subsets_Mito_percent     total   discard sizeFactor       Phase  G1.score G2M.score   S.score    label elbowlabel
             <numeric> <numeric> <logical>  <numeric> <character> <numeric> <numeric> <numeric> <factor>   <factor>
1              3.25000      2400     FALSE   0.612746          G1     0.821     0.337     0.165        7          9
2              3.42067      1374     FALSE   0.392857          G1     0.626     0.526     0.151        9          6

> str(genes)
 chr [1:50] "LYZ" "CST3" "LGALS1" "TYROBP" "S100A4" "IGLL1" "VPREB1" "CD79B" "PTMA" "STMN1" "SPINK2" "RPS24" ...
```

and the versions I'm using:

```
> packageVersion('dittoSeq')
[1] ‘1.6.0’
> BiocManager::version()
[1] ‘3.14’
> 
```

I've gotten the heatmap to work just a few days ago. I don't think I've updated any packages or versions.  Not sure what to try next.

Thank you,

**Comment by dtm2451** [comment]
Hmmm I've definitely seen that error message before and it generally means one of your indexes is invalid.  Does `all(isGene(genes, sce.symbol))` give TRUE?

**Comment by pcantalupo** [comment]
yep 
```
isGene(genes, sce.symbol)
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[24] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE
[47] TRUE TRUE TRUE TRUE
> all(isGene(genes, sce.symbol))
[1] TRUE
```

**Comment by dtm2451** [comment]
Hmmmm... oh!  I think I got it.

> ```
> > sce.symbol
> class: SingleCellExperiment 
> dim: 12212 1866 
> metadata(1): Samples
> assays(2): counts logcounts
> rownames(12212): AL627309.1 RP11-206L10.9 ... AL354822.1 SRSF10
> rowData names(6): ID Symbol ... discard hvgs
> colnames: NULL
> ```

It's that you don't have colnames.  That's what goes into the `cells.use` of the erroring call.

Try running

```
colnames(sce.symbol) <- paste0("cell_", seq_len(ncol(sce.symbol)))
```
and then try again.

**Comment by dtm2451** [comment]
This has come up a few times now, also #102, so I suppose my assumption that most pipelines will end up giving colnames to the SCE might as well be double-checked. (dittoSeq regularly looks to these in order subset to `cells.use` and to ensure it keeps data aligned properly across any reshaping.)  I'll work in either 1) an error which catches and explains that you'll need to add colnames, or 2) a fix which adds them internally when missing, soon!

**Comment by pcantalupo** [comment]
It works now when adding colnames!  I remember a few days ago setting the colnames in a script. That is probably when dittoSeq worked for me.  Thank you!

**Comment by dtm2451** [comment]
Just pushed the error-add which should make it through the build system in a few days as v1.8.1 (and devel 1.9.1).  In those and future versions, the error generated when colnames are missing will be consistent & easier to understand, and it'll include the `colnames(<object>) <- paste0('cell', seq_len(ncol(<object>)))` code suggestion as well =)
