### ISSUE TITLE
dittoBoxPlot() ....for multiple genes??? 

### ISSUE THREAD

**Issue by levinhein** [dtm2451/dittoSeq#111]
Hello. I'm currently applying your wonderful tool for my project. I tried to use dittoBoxPlot() and it appears it can only be used for 1 gene at a time per plot. 

I want to compare/display the expression levels of several DEGs across conditions (healthy and disease) in one plot such that it looks like the below figure:

...where y-axis is the expression levels, and the x-axis should be the genes (and each gene has 2 barplot of healthy and disease). Hence, similar to this boxplot, generating a pattern where the blue boxplots of healthy states are low, and the red boxplots of upregulated DEG genes in diseased are high.

Could you please help me? Thank you very much in advance!

![image](https://user-images.githubusercontent.com/68268222/176076447-e40548b5-3045-40c0-93a8-bd257991ed45.png)

**Comment by dtm2451** [comment]
Hi there!  It's not possible currently, but seeing as this is the 2nd time this `enhancement` has been asked for #99, configuring for this use case has just jumped to the top of my dittoSeq ToDo list.  Hard to give an ETA rn, but probably some time in the next month.

**Comment by levinhein** [comment]
Thank you very much for considering. Very interested with it and really looking forward! 

Have a nice day, Daniel!

**Comment by dtm2451** [comment]
I've put together a version of how this could work.  You can try by installing via `BiocManager::install("dtm2451/dittoSeq@multivar-dittoPlot")`. Just remember to restart your session after the installation if you already had dittoSeq loaded.

**Comment by levinhein** [comment]
Hi Daniel! Thank you, I’ll do that!

May I know the scripts on how to implement or make the Boxplots for multiple genes?

**Comment by dtm2451** [comment]
To make a plot like what's above, you probably need something like

```
dittoBoxPlot(
    object = <your_data>,
    var = c("<gene1>", "<gene2>", "<gene3>"),
    group.by = "<metadata_for_your_subgroups>",
    multivar.aes = "group")
```

Options for `multivar.aes`, which controls the part of the plot used to display your `var`s, are "group", "color", and "split".
