### ISSUE TITLE
About 

### ISSUE THREAD

**Issue by Pedramto89** [dtm2451/dittoSeq#118]
Hi
I want to visualize some clusters of interests out of the seurat obj but when I specify them by "idents", it still shows all the clusters. 
Is there any way to do this?

This is the code I run and get no error btw!
`dittoHeatmap(obj, genes = NULL, metas = names(ES.seurat),  
              annot.by = "seurat_clusters",  fontsize = 7,  
              idents = c(8,9), cluster_cols = TRUE,  #modified this line, accidentally capitalized idents.
              heatmap.colors = colors(50))`

And this is the heatmap I get:
![image](https://user-images.githubusercontent.com/85902042/219875734-a274221b-44c2-4dfc-bf48-78e7d3e1a5bb.png)

**Comment by dtm2451** [comment]
Hey there!  The dittoSeq input for this is called `cells.use`, not idents.  Seems to me like `cells.use = obj$seurat_clusters %in% c(8,9)` should get you what you want!

It's definitely unfortunate that this function gives no errors for incorrectly named inputs!  It's a side-effect of other important functionality.  There's a `...` input that allows users to add pheatmap inputs which then get passed to the internal `pheatmap()` call.  R turns off showing 'unused argument' errors when `...` is used by a function.

**Comment by Pedramto89** [comment]
Hi @dtm2451 Thank you so much it worked!

**Comment by dtm2451** [comment]
Wonderful!  Happy plotting =)
