### ISSUE TITLE
X values in dittoBarPlot not ordering according to x.reorder

### ISSUE THREAD

**Issue by zoqaiyum** [dtm2451/dittoSeq#121]
Hello, 

I am seeking to create a bar plot of different Phenograph clusters across different samples. My SCE object is called "sce2", Phenograph clusters are in the variable "pg_clusters_corrected", and samples are in the variable "sample_id". 

This is what my SCE object looks like where pg_clusters_corrected (annotated with purple rectangle) is located within colData: 

<img width="845" alt="Screenshot 2023-08-11 at 3 45 18 PM" src="https://github.com/dtm2451/dittoSeq/assets/119648999/aaeb9417-ac79-4ddf-a1ba-9c7473ce3866">

My code for barplot "a" below:
```
a<- dittoBarPlot(sce2, var = "sample_id", group.by = "pg_clusters_corrected",x.reorder = c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15),retain.factor.levels = TRUE, x.labels.rotate = FALSE) +
    scale_fill_manual(values = metadata(sce2)$color_vectors$sample_id) +
    scale_y_continuous(breaks = seq(0, 1, by = 0.25), labels = c('0', '25', '50', '75', '100'))
a
```

This code above gives me this plot "a": 
![image](https://github.com/dtm2451/dittoSeq/assets/119648999/4156be8c-9f1d-416d-968f-3f4daa7fafad)

Now, I am interested in plotting only a subset of the total 15 clusters, i.e. I only want to plot clusters 2,3,5,9,13 (in this order). So I first began by creating a new SCE object, "u": 
```
#Filtering sce2 to only look at specific phenograph clusters 
u <- sce2[,sce2$pg_clusters_corrected == "2"|sce2$pg_clusters_corrected == "3"|sce2$pg_clusters_corrected == "5"|sce2$pg_clusters_corrected == "9"|sce2$pg_clusters_corrected == "13"]

```
 

Codes for plot "b" below: 
```
b<- dittoBarPlot(u, var = "sample_id", group.by = "pg_clusters_corrected",retain.factor.levels = TRUE,x.labels.rotate = FALSE) +
    scale_fill_manual(values = metadata(u)$color_vectors$sample_id) +
    scale_y_continuous(breaks = seq(0, 1, by = 0.25), labels = c('0', '25', '50', '75', '100'))
b
```
Code above gives me this plot "b": 
![image](https://github.com/dtm2451/dittoSeq/assets/119648999/39db6bb5-57d3-4579-a7bc-3d47cbb05346)

As you can see, plot "b" only removed the irrelevant clusters without modifying the x-axis. I want to have only 2,3,5,9,13 appear in the x-axis. As an attempt to rectify this, I tried plotting plot "c" (code below): 
```
c<- dittoBarPlot(u, var = "sample_id", group.by = "pg_clusters_corrected", x.reorder = c(2,3,5,9,13),x.labels.rotate = FALSE) +
    scale_fill_manual(values = metadata(u)$color_vectors$sample_id) +
    scale_y_continuous(breaks = seq(0, 1, by = 0.25), labels = c('0', '25', '50', '75', '100'))
c
```
Code above gave me the plot "c": 
![image](https://github.com/dtm2451/dittoSeq/assets/119648999/b629cf98-2b3f-45a4-99c1-66147af6f056)

As you can see, with plot "c", I have managed to have the x-axis only focus on my clusters of interest, but then appears to group cluster 5 and 13 together making it "NA". Another further attempt to fix this using the code below: 
```
d<-dittoBarPlot(u, var = "sample_id", group.by = "pg_clusters_corrected", x.reorder = c(2,3,5,9,13),retain.factor.levels = TRUE, x.labels.rotate = FALSE) +
    scale_fill_manual(values = metadata(u)$color_vectors$sample_id) +
    scale_y_continuous(breaks = seq(0, 1, by = 0.25), labels = c('0', '25', '50', '75', '100'))
d
```

However, now this code for plot "d" gives me this error: 
Error in .rename_and_or_reorder(data$grouping, x.reorder, x.labels) :
incorrect number of indices provided to 'reorder' input

How can I make this bar plot so that only clusters 2,3,5,9,13 are visible on the x-axis? Any help is much appreciated. Many thanks!

**Comment by dtm2451** [comment]
Did you add `retain.factor.levels = TRUE` in your dittoBarPlot call?

```
dittoBarPlot(sce2, var = "sample_id", group.by = "pg_clusters_corrected", retain.factor.levels = TRUE)
```

**Comment by dtm2451** [comment]
For why `x.reorder` didn't do anything for you, it expects to take in indexes of the groupings, not their actual values.  (I've also grown to realize this methodology is un-intuitive, so this is another pain-point that I may adjust in 'v2'.  I just haven't decided how yet.)  Based on the plot you shared above, and there's really no other way to learn how to use this input without first generating a plot that doesn't use it, would be to give `x.reorder = c(1, 7:15, 2:6)`.

That said, making your target data a factor is the better way, and it's only `dittoBarPlot()` where actually making use of your factor levels requires this additional  "add `retain.factor.levels = TRUE`" step.

**Comment by zoqaiyum** [comment]
@dtm2451 Hi Daniel, many thanks for the tip. I have added that and the reordering works now, however now I have another issue. I have amended my original post with this new query. Any help with that would be welcome. Thanks!

**Comment by dtm2451** [comment]
You can use `droplevels()` to remove the empty levels.
```
u$pg_clusters_corrected <- droplevels(u$pg_clusters_corrected)
```

**Comment by zoqaiyum** [comment]
That worked! Thanks once again!

**Comment by dtm2451** [comment]
The other thing I want to flag for you: Instead of giving your colors via a call to `+ scale_fill_manual(values = metadata(u)$color_vectors$sample_id)` which would override accessibility adjustments in other plot types, you can use `color.panel = metadata(u)$color_vectors$sample_id` in your dittoSeq function calls!
