### ISSUE TITLE
Throw error if dimReds are NA

### ISSUE THREAD

**Issue by ATpoint** [dtm2451/dittoSeq#122]
Hello ditto-people,

a suggestion based on https://support.bioconductor.org/p/9153800/#9153824 -- there should be an informative error/warning when using `dittoDimPlot()` but there is no dimred present in the input object. 

cheers,
Alex

**Comment by ATpoint** [comment]
https://github.com/dtm2451/dittoSeq/pull/123

**Comment by dtm2451** [comment]
Hadn't even noticed the support Q yet and you've already PR'd, thanks so much!  I need to tweak a bit before merging into the 'devel' and release barches, so please re-base toward the new `dimred-fix` branch as I'll note on the PR as well.

**Comment by ATpoint** [comment]
https://github.com/dtm2451/dittoSeq/pull/124
