### ISSUE TITLE
How to remove median in boxplot?

### ISSUE THREAD

**Issue by Dexiao211** [dtm2451/dittoSeq#132]
Thanks for developing this package. Now, I want to generate a box and scatter plot for a Seurat object using 'dittoplot.' Can you tell me how to remove the median in the boxplot? Thanks.

**Comment by dtm2451** [comment]
Hiding the median is not a built-in feature.

For the other part of your question, I'm not sure if I understand what you mean by "I want to generate a box and scatter plot ... using 'dittoplot.'," but if I'm correctly assuming that you mean box and *jitter, then to have the boxplot in front you can use:
```
dittoPlot(..., plots = c("jitter", "boxplot"))
```
Or, if you want the boxplot behind the per-cell jitter, then either swap the order or use the dittoBoxPlot wrapper that works exactly like dittoPlot aside from having c("boxplot", "jitter") as its default for this `plots` input.
```
dittoPlot(..., plots = c("boxplot", "jitter"))
dittoBoxPlot(...)
```

**Comment by Dexiao211** [comment]
Thank you very much; I appreciate it. Can you please tell me how to change the size of the dots in 'dittoplot'?

**Comment by dtm2451** [comment]
Luckily, this seems easy enough to do with the ggplot boxplot geom manually.  Code below.

**If you don't mind, could you explain why you want to hide your medians?**

I will think about whether this is worth building into the package.  Currently, I'm unsure of the reasoning behind your use-case, so thinking it may be quite uncommon and not worth adding to the package.

This code generates the jitter-points via dittoSeq, then uses a direct call to geom_boxplot() afterwards to generate the boxplots without showing the medians.  Comes with a warning about missing data points that is a direct result of the use of `NA` here to hide those values:
```
# Example using Seurat's toy dataset
dittoPlot(pbmc_small, var = "HLA-DRA", group.by = "groups", plots = "jitter") +
  geom_boxplot(middle = NA)
```

**Comment by dtm2451** [comment]
> Can you please tell me how to change the size of the dots in 'dittoplot'?

`jitter.size` input.  Please take a look at `?dittoPlot`

**Comment by Dexiao211** [comment]
Thanks.

**Comment by Dexiao211** [comment]
> Luckily, this seems easy enough to do with the ggplot boxplot geom manually. Code below.
> 
> **If you don't mind, could you explain why you want to hide your medians?**
> 
> I will think about whether this is worth building into the package. Currently, I'm unsure of the reasoning behind your use-case, so thinking it may be quite uncommon and not worth adding to the package.
> 
> This code generates the jitter-points via dittoSeq, then uses a direct call to geom_boxplot() afterwards to generate the boxplots without showing the medians. Comes with a warning about missing data points that is a direct result of the use of `NA` here to hide those values:
> 
> ```
> # Example using Seurat's toy dataset
> dittoPlot(pbmc_small, var = "HLA-DRA", group.by = "groups", plots = "jitter") +
>   geom_boxplot(middle = NA)
> ```
Because I want to plot then mean instead of median. Sorry for my late reply.

**Comment by dtm2451** [comment]
Gotcha!  That's a fair reason.  I will consider officially baking this in, which is also why I've just figured out if I could give you better code here =).

FYI this seems like a more full way to do that -- now including the plotting of mean, and dittoSeq styling:
```
# Replace median with mean
dittoPlot(pbmc_small, var = "HLA-DRA", group.by = "groups", plots = c("jitter"), sub = "thick line at mean") +
    geom_boxplot(
        fatten=NULL, # another way to turn off the median plotting, though it still doesn't block the warning
        # Adding in some dittoSeq default styling
        width = 0.2, # This would normally be controlled with dittoSeq's boxplot.width input, but we can't inherit that here.
        size = 1, # This would normally be controlled with dittoSeq's boxplot.lineweight input.
        color = "black" # This would normally be controlled with dittoSeq's boxplot.color input.
    ) +
    stat_summary(
        fun="mean",
        geom = "errorbar",
        aes(ymax = ..y.., ymin = ..y..),
        size = 2, width = 0.2)

# versus
dittoPlot(pbmc_small, var = "HLA-DRA", group.by = "groups", plots = c("jitter", "boxplot"), sub = "thick line at median")
```

Gives:
![image](https://github.com/dtm2451/dittoSeq/assets/38870347/8d83792e-61b8-48c0-a52a-1bd5e22713a9)
versus, original:
![image](https://github.com/dtm2451/dittoSeq/assets/38870347/ec18b493-7bd7-41db-80fd-e53e749d86ae)
