### ISSUE TITLE
Add parameter to control boxplot outlier size

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/dittoSeq#133]
No way to control this currently (at least that I am aware of). Be fairly simple to add a parameter pass to the boxplot call to control this:
`geom_boxplot(outlier.size = 0.1)`

**Comment by dtm2451** [comment]
Yep, this should be a very simple add.  I can probably create a branch at least with it worked in today.

**Comment by dtm2451** [comment]
Branch in called `boxplot-outlier-size`, so `remotes::install_github("dtm2451/dittoSeq@boxplot-outlier-size")` to install.
Input = `boxplot.outlier.size`.

I also decided to fold in here a `vlnplot.quantiles` input that I've been meaning to add for a while =)

Example:
```
library(dittoSeq)
example(importDittoBulk, echo = FALSE)
dittoPlot(
    object = myRNA, var = "gene1", group.by = "timepoint", plots = c("vlnplot","boxplot"),
    boxplot.outlier.size = 5,
    vlnplot.quantiles = c(0.1, 0.9)
)
```
![image](https://github.com/dtm2451/dittoSeq/assets/38870347/077ec618-fd1b-466b-a264-b5883c828316)
