### ISSUE TITLE
Error generating dittoheatmap

### ISSUE THREAD

**Issue by yeaehan** [dtm2451/dittoSeq#137]
Hi everyone,

I'm trying to plot my Seurat object with dittoHeatmap. I'm able to plot it with other plotting functions on dittoSeq such as dittoPlot with no issue, but I keep getting an error with dittoHeatmap.

Just for additional information: 
- I've used the EnrichIt function from the 'escape' package for enrichment, and the results are stored in ES and added to the seurat_object with the AddMetaData() function

```
###WORKS
dittoPlot(seurat_object, names(ES), group.by="cluster_id")

###DOESN'T WORK
dittoHeatmap(seurat_object, genes=NULL, metas = names(ES), 
             annot.by = "cluster_id", cluster_cols=TRUE,
             fontsize = 7)

###the error message
Warning: no non-missing arguments to min; returning InfWarning: no non-missing arguments to max; returning -InfError in seq.default(-m, m, length.out = n + 1) :

```

I can't figure out what the issue is :'( please help

**Comment by dtm2451** [comment]
Is one of the `metas` you are trying to plot from a constant number for all cells, or all NAs?  I can get what looks like the same error with:
```
library(dittoSeq)
example("importDittoBulk", echo = FALSE)
myRNA$test <- 5
dittoHeatmap(myRNA, metas = c("test", "test", "test"), genes = NULL)
```
The error I see:
```
Error in seq.default(-m, m, length.out = n + 1) : 
  'from' must be a finite number
In addition: Warning messages:
1: In min(x, na.rm = T) : no non-missing arguments to min; returning Inf
2: In max(x, na.rm = T) : no non-missing arguments to max; returning -Inf
```

I'm hopeful, but also doubt this would be your issue as you probably would have noticed something seemed weird in that case when looking at your `dittoPlot()` output...

**So if that doesn't stir up anything helpful for you**, could you describe what are the metadata pointed to with `names(ES)`, either in words or even better by sharing the output of `summary(seurat_object@meta.data[,names[ES],drop=FALSE])`? I think that would be the most helpful thing for me to understand what's happening.

**Comment by yeaehan** [comment]
Hi, thank you so much for your response! 

I didn't have any NA in the values for my data, but upon checking, I noticed that the the name of the list within ES was 'NA.' (not sure why) and that's what must have been throwing the errors!!! I fixed that and finally got the heatmaps. :') Thank you so much!!!!!!!!!!!!!
