### ISSUE TITLE
interactive heatmap 

### ISSUE THREAD

**Issue by shengyongniu** [dtm2451/dittoSeq#152]
Hi there,
I am interested in selecting some genes after the visualization of dittoheatmap based on the gene clusters. Too many genes (~300) are in the heatmap, so it's hard to know them by label. I wondered if there's an interactive mode I can use to select and understand what these genes are. Thank you

**Comment by dtm2451** [comment]
Hi there,

One option is to make use of `complex = TRUE` in your `dittoHeatmap()` call and then use `InteractiveComplexHeatmap`, the Shiny app companion for `ComplexHeatmap`.  I haven't used this much yet myself, but it looks super cool!  There's a vignette [here](https://jokergoo.github.io/InteractiveComplexHeatmap/).

Eventually I will find time to address #101 properly, but in the meantime, if it would be helpful to label only specific genes after you pick them out, there's some code in that issue for making use of ComplexHeatmap's more robust labeling system.

**Comment by shengyongniu** [comment]
I just try it, it's pretty nice! Thanks!
