### ISSUE TITLE
dittoheatmap label color

### ISSUE THREAD

**Issue by shengyongniu** [dtm2451/dittoSeq#153]
Hi there,
I was wondering if there's a way to change the color of the top bar of the dittoheatmap? The two colors are not distinguishable enough for me. Thank you.

<img width="1323" alt="image" src="https://github.com/dtm2451/dittoSeq/assets/10880134/b7384500-03ba-4d39-9db7-46734ed5ff5e">

**Comment by dtm2451** [comment]
Yes, and in a couple ways:
1. The colors automatically chosen by dittoSeq, if you do not use option2 below, for the annotation bars are chosen from among the colors given to the `annot.colors` input.  You can give your own vector of colors here.  In the automated color picking, set by set, colors are taken from that vector and assigned to their component values.
2. The pheatmap input `annotation_colors` is ultimately what is used for telling pheatmap what colors to use.  You can provide that input directly for some or all of your requested annotations. (The system described above is only used for the annotation sets that you have not manually provide colors for). If you would like to be explicit about what color is used for what, this is the best way.

An example of how to set `annotation_colors` for a case where I had `annot.by = c('Inflammation', 'Malperfusion')` and each contained values of 'Y' or 'N' would be:
```
dittoHeatmap(
  ...,
  annotation_colors = list(
    'Inflammation' = c(
      'Y' = dittoColors(1)[7],
      'N' = "white"
    ),
    'Malperfusion' = c(
      'Y' = dittoColors(1)[8],
      'N' = "white"
    )
  )
)
```

As can be seen in the "white"s, you don't have to use dittoColors() elements as I did for the "Y"s.  Anything that R accepts as a color should work.

Setting up this `annotation_colors` structure for numeric annotations is more complicated, so I definitely recommend just adjusting the `annot.colors` input for those cases instead -- colors for numeric data get pulled from the far end of the color vector -- but that doesn't seem necessary for your case here!
