### ISSUE TITLE
dittobarplot color

### ISSUE THREAD

**Issue by shengyongniu** [dtm2451/dittoSeq#154]
Hi there,
I generated a UMAP from Seurat and want the plot from dittoBarPlot to match the color for each cell cluster. Is there any way to match the color?
I can extract the color of the cluster from UMAP like this, but I am not sure how to assign it to the bar plot. Thanks!

```
require(scales)
# Create vector with levels of object@ident
identities <- levels(object@ident)
# Create vector of default ggplot2 colors
my_color_palette <- hue_pal()(length(identities))
```

**Comment by dtm2451** [comment]
I notice you closed this issue which likely means you realized how to do this.  (`color.panel` input if not or for anyone else ending up here in the future!)

But I feel the need to still chime in and say that **the better approach is the opposite, of using the color blindness-accessible colors from `dittoColors()` in your Seurat plots**.  The rainbow-style default colors of Seurat are patently NOT ACCESSIBLE colors beyond a certain number, with that just getting worse and worse as the number of levels increases.  From my perspective, swapping to `hue_pal()` would objectively make your plots worse, and doing so is quite antithetical to the instigator of my writing dittoSeq functions in the first place (my own protanomalous eyes & temporarily broken color controls of Seurat functions).

Unless your data has 4 or fewer levels -- the rainbow-style default colors of Seurat are a bit more 'okay' from an accessibility perspective below 5 colors -- please do not follow through with this color swap.
