### ISSUE TITLE
Feature request: capacity to drop elements from the legend directly

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/DittoSeq#16]
The "proper" way to achieve this is to muck with the factor levels of the variable in question [directly](https://stackoverflow.com/questions/21801950/remove-legend-entries-for-some-factors-levels), which is at best annoying and time-consuming. 

The ability to drop legend elements directly with functionality similar to the current `rename.groups` implementation in `DBBarPlot` would be extremely convenient, particularly when subsetting.

**Comment by dtm2451** [comment]
`dittoBarPlot()` is up!  It should fix this issue for you.

Before plotting but after `cells.use` subsetting, the updated function converts both the x.data and y.data to a character and then (back) to a factor.  Doing so eliminates unused levels, which I believe was the root cause of this issue.
