### ISSUE TITLE
Anaconda recipe request

### ISSUE THREAD

**Issue by elzerac** [dtm2451/dittoSeq#17]
Could you make a recipe through anaconda to install dittoseq? Or will this be a feature that will be available once this is on bioconductor?

**Comment by dtm2451** [comment]
It's not dependent on bioconductor, but I want to make dittoSeq a bit more finalized first.

I'm going to be ready to submit to CRAN in the next couple weeks.  And I'll look into this after that!

**Comment by dtm2451** [comment]
Update: I've submitted dittoSeq to Bioconductor.  I'll look into recipe creation once it's in there.

**Comment by dtm2451** [comment]
Having confirming with you directly that you are fine with installing from within R, I'm closing this issue.
