### ISSUE TITLE
Seurat 3.0

### ISSUE THREAD

**Issue by kravarik** [dtm2451/DittoSeq#2]
This is great - I can't wait to start using this to make better plots. Do you plan to release a version that is compatible with Seurat 3.0.x?

**Comment by dtm2451** [comment]
I do!  Perhaps I'll have it up in the next month or so?  Working on it now, but as you probably know, Seurat v2 -> v3 was a pretty major update.

**Comment by dtm2451** [comment]
Updated!
All the tests I've run so far seemed fine, just wanna run a bit more tomorrow before I close the issue.

Let me know if you have any issues.

**Comment by kravarik** [comment]
Thanks so much - I will give it a try!

**Comment by dtm2451** [comment]
As far as I can tell, the visualization functions work for v3 and v2 objects!

I am having issues with the Demuxlet-import functions.  I think it may be a bug in the merge() Seurat code.  Im not sure, but I plan to sort it our or make a work-around in the next week.

**Comment by dtm2451** [comment]
Demuxlet-import functions should work now =).
