### ISSUE TITLE
Creating dittoDimPlots with larger color vectors?

### ISSUE THREAD

**Issue by rebeccagj** [dtm2451/dittoSeq#28]
I recently encountered an instance where I was trying to make a `dittoDimPlot` which required 78 separate colors. I got the error `Error: Insufficient values in manual scale. 78 needed but only 24 provided`. I was able to manually concatenate some other color hexes with `dittoColors()`, but I'm wondering if larger color vectors might be possible in the future?

In case anyone runs into this, here's the code I used.
```
library(RColorBrewer)
qual_cols = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_cols$maxcolors, rownames(qual_cols)))
col_vector = c(dittoColors(), col_vector)
```
You can then pass `col_vector` to `dittoDimPlot`. Disclaimer, I don't think these colors are color-blind friendly anymore ):

**Comment by dtm2451** [comment]
There's a real struggle with growing the color panel larger while staying color-blind friendly.

Really, even the 24 colors already in dittoSeq don't do this perfectly.  (Some of the original brightness colors (1:8) are hard to distinguish from lighter or darker variants (9:24)). Even for non-color impaired individuals, I've heard from a few of you that once one gets above 15 colors, it gets quite hard to tell all colors apart of any color panel anyway... So I'm on the fence about whether it's worth always adding new unique colors.

Accepting that perfection here is impossible, what I think I can do is to grow the default color panel a little bit more, with further lightened / darkened versions, then simply add 100 repeats. Then, the values need would grow to over 2500 colors before the panel would error as too short.

Eventually, working in an automatic split, by point shape or by fill pattern, would be even better, but I'll have to think about the best way to implement that.

**Comment by dtm2451** [comment]
I have added colors to bring the total number of unique colors to 40.  Then these are repeated.  Can you try this panel on your data and let me know what you think @rebeccagj?

For your current application would you prefer all individual colors to truly be distinct, or is this enough?

**Comment by rebeccagj** [comment]
Hi @dtm2451, sorry for my delayed reply. The closer I can get to true distinction the better. I'm testing `singleR` fine label predictions on one of my datasets, and it assigns quite a few different cell types! So having truly distinct colors helps me pick what labels I think are real.

I think my ideal would be for dittoSeq to have even more distinct colors, but I'm cognisant that at some point, it does get hard for even cone-typical individuals to distinguish color differences.

**Comment by dtm2451** [comment]
Hmmm. I do wonder if you would actually be able to tell the additional colors apart.

Alternatively perhaps you could mix in `cells.use`, `shape.by`, or `split.by` instead to help discern the extra groups?

- `cells.use` would probably be the easiest to discern.
- `split.by` would give you something similar to shape.by, but since we've chatted offline I happen to know that you are using v0.3, and you don't have that option.
-  `shape.by` probably gives the publishable all-in-one-plot version, but IMHO it won't be the easiest to actually interpret.

```
# Let's say you were using 'var' = "labels"
myRNA$extra.split <- array("1", ncol(object))
myRNA$extra.split[object$labels %in% meta.levels("labels", object)[1:40]] <- "2"

# And so on if needed...
myRNA$extra.split[object$labels %in% meta.levels("labels", object)[41:80]] <- "3"

# note: meta.levels becomes metaLevels in v0.99+

# For shape.by or split.by, you will want the 1/2/3... appended to the labels
object$labels <- paste(myRNA$label, myRNA$extra, split = "-")

dittoDimPlot(object = object, "labels",
    cells.use = myRNA$extra.split == 1) # (Then repeat with ==2, ==3, and so on)
    # OR
    shape.by = "extra.split") #
    # OR
    # split.by = "extra.split") #
```

**Comment by rebeccagj** [comment]
Yeah, I think splitting / subsetting the plot using `cells.use` makes the most sense for my usage. There are a lot of classifications in my current dataset that I think are false based on what I know of the biology of my cells. So really, I just need to subset so that I don't have colors repeated, then chip away at those false labels. I think once I complete that, I would be well within the 40 distinct colors that `dittoColors()` calls, and would cease to be troubled by the repeating issue.

**Comment by dtm2451** [comment]
Awesome!

I'd love to hear from anyone else that needs lots of colors too.  I'll likely be merging in this fix as is, but am certainly open to further suggestions now and in the future.

@j-andrews7, do you find dittoColors() sufficient for detecting clonal relationships in your Tcell datasets with TCRs?

**Comment by j-andrews7** [comment]
Generally, I end up collapsing clonotypes (since there are often 100's or 1000's) to a few colors based on the majority clones. I basically have a function that keeps the unique sequences for clonotypes frequencies > 0.1%, then just label all the rest (unique clonotypes only in 1 or 2 cells) as "Other". So I rarely even repeat any longer, as I never have > 10 pops for that any longer. 

I think an expanded set of 40 is still very useful, and I will test other applications with this. I have >30 clusters with all my samples together, so I will test it on that.

**Comment by rebeccagj** [comment]
Thanks for the quick reply @dtm2451, and I certainly appreciate the fix!

**Comment by dtm2451** [comment]
I'm going to assume the 40 color-set (with repeating to keep errors from occurring until >4,000 are needed) was deemed sufficient and close this issue for now. But if my assumption is wrong, another update can certainly be made in the future.
