### ISSUE TITLE
DimPlot can't do both split.by and do.label

### ISSUE THREAD

**Issue by jdrnevich** [dtm2451/dittoSeq#47]
I was running through your vignette and tried to both split.by = "Sample" and then add do.label = TRUE but got this error:

```
dittoDimPlot(seurat, "celltype", split.by = "Sample")
#this works fine

dittoDimPlot(seurat, "celltype", split.by = "Sample", do.label = TRUE)
Error: Aesthetics must be either length 1 or the same as the data (20): label
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Aesthetics must be either length 1 or the same as the data (20): label
Backtrace:
  1. (function (x, ...) ...
  2. ggplot2:::print.ggplot(x)
  4. ggplot2:::ggplot_build.ggplot(x)
  5. ggplot2:::by_layer(function(l, d) l$compute_geom_2(d))
  6. ggplot2:::f(l = layers[[i]], d = data[[i]])
  7. l$compute_geom_2(d)
  8. ggplot2:::f(..., self = self)
  9. self$geom$use_defaults(data, self$aes_params, modifiers)
 10. ggplot2:::f(..., self = self)
 11. ggplot2:::check_aesthetics(params[aes_params], nrow(data))
Run `rlang::last_trace()` to see the full context.

```
The error comes when trying to plot the ggplot object created by dittoDimPlot(), because dittoDimPlot() itself doesn't trigger the error:

```
> p <- dittoDimPlot(seurat, "celltype", split.by = "Sample", do.label = TRUE)
> p
Error: Aesthetics must be either length 1 or the same as the data (20): label
Run `rlang::last_error()` to see where the error occurred.
```
It must be able to be done because Seurat's DimPlot can both split and label

```
DimPlot(seurat, label = TRUE, split.by = "Sample", ncol = 2)
```

I've just started trying out your package and really like it! I personally do not need it for the color-blindness aspect, but it does a much better job at selecting contrasting colors for close clusters.

**Comment by dtm2451** [comment]
Thanks for pointing this out!

Based on how the labels in Seurat's version move around across the facets, it seems their implementation of the labeling is quite different.  So I see two potential paths forward: 1) have the label-center calculations performed by ggplot as I suspect Seurat does, or 2) simply duplicate the label locations dataframe that dittoSeq calculates for each of the eventual facets. But also `do.labels` was one of my earliest feature additions so it's possible there is a literal bug somewhere and this may be an easier fix.

I'll look into this more and see what I can do, but it would help me to decide between which method if you can tell me more about your target use case. Specifically, I'm wondering if it would be better for the label locations to 1) shift around based on the data within each facet, as in the below plot from Seurat, or 2) remain in the same 'all-data' centers across all facets?

```
# Seurat version:
Idents(seurat) <- "celltype"
DimPlot(seurat, label = TRUE, split.by = "Sample", ncol = 2)
```
![image](https://user-images.githubusercontent.com/38870347/88315216-df4c4880-ccca-11ea-99fe-dabb7ad75cf6.png)

**Comment by jdrnevich** [comment]
I think I would lean towards the shifting on the data within each facet in general, although in this example you get some weird placements when there are few cells, like the acinar in the right two samples. I have had a couple of experiments where one of the samples had 0 cells in a cluster, so how would that be handled? If would be easier to just place the labels based on the aggregate data before faceting, that would be fine too.

Looking forward to your talk next week!

Jenny

**Comment by dtm2451** [comment]
I've implemented a shift-per-facet method, and I currently have it in the `dimplot-feature-update` branch.  If you'd like to use / test, you can install via `devtools::install` or `BiocManager::install("dtm2451/dittoSeq@dimplot-feature-update")`.

Before I merge it in fully, I need to troubleshoot an error the comes with splitting by multiple metadata. But that's something Seurat doesn't allow anyway 🙃. 

This may not matter for you, but I've added a `labels.split.by` input (which defaults to the regular `split.by`) to allow separation of control of the per-facet calculations from `split.by` when needed. Theoretically, this allows the faceted labelling to still work for users gunning for extra control over their faceting via `dittoDimPlot(..., extra.vars = c(var1,var2), do.label = TRUE, labels.split.by = c(var1,var2)) + manual_facet_code_using(var1,var2)`.

**Comment by jdrnevich** [comment]
Thanks! I'll try it out next week during BioC talks I am less interested in :)

**Comment by dtm2451** [comment]
I figured the multi-metadata splitting issue out too!  The fixes are merged into master, and by the time the conference starts, this fix should be in Bioconductor devel, version 1.1.4.

**Comment by mbartl13** [comment]
Hi, I tried this but got the following:
`dittoDimPlot(bm280k.integrated,extra.vars = c("sample","ident"), do.label=TRUE,labels.split.by = c("sample","ident")) + manual_facet_code_using("sample","ident")
`
Error in .leave_default_or_null(main, var, length(var) != 1) : 
  argument "var" is missing, with no defaul

**Comment by mbartl13** [comment]
Thanks, still a bit confused. I added made variables for the two meta features but am getting the same error?
`var1<-pbmc.combined_CP$sample
var2<-pbmc.combined_CP$orig.ident
dittoDimPlot(pbmc.combined_CP,do.label=TRUE,extra.vars = c(var1,var2),labels.split.by = c(var1, var2)) + manual_facet_code_using(var1, var2)
`
Error in .leave_default_or_null(main, var, length(var) != 1) : 
  argument "var" is missing, with no default

**Comment by dtm2451** [comment]
Sorry, a bit confusing I suppose, but `extra.vars` and `var` are distinct inputs.
Try giving
```
dittoDimPlot(bm280k.integrated, var="sample", extra.vars = c("sample","ident"), do.label=TRUE,labels.split.by = c("sample","ident")) + manual_facet_code_using("sample","ident")
```
(added `var = "sample"`)

Also note that `extra.vars` needs to be given a string vector of metadata or gene names, so the method in your most recent [comment](https://github.com/dtm2451/dittoSeq/issues/47#issuecomment-1112488219) would break an `extra.vars` step later on.

**Comment by mbartl13** [comment]
Got it! Thanks
