### ISSUE TITLE
Add warning for providing a single variable to multi-plotters

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/dittoSeq#52]
As it stands, providing a single variable to the multiplotters results in a somewhat cryptic error and tends to cause R to hang/crash on occasion. A more explicit warning would be helpful. Falling back to the appropriate single variable function would be an elegant, though more obfuscated, way to get around this as well.

**Comment by dtm2451** [comment]
This is a great idea. Falling back to the single potters via a non-lapply call here may actually be pretty simple, so I'll see what I can do.

I should probably also add some more robust unit-tests for the multi_plotters as I don't think there is much at all for them now...

(As I know you know, but others don't...) I've been busy graduating and then starting a new job, but I will tackle this soon!!

**Comment by dtm2451** [comment]
As far as my testing went, multi_dittoPlot & multi_dittoDimPlot both work fine when given a length 1 `vars`.  But... I still made some updates to the code and docs and examples for these and other functions. And I'm going to merge them in.

But do let me know if you can recreate the error that you'd gotten!

**Comment by j-andrews7** [comment]
Going to close this as I can't remember/reproduce the error. So it could have been a quirk of my data/SCE object. If I run into it again, I will open again.
