### ISSUE TITLE
could not find function "dittoDotPlot"

### ISSUE THREAD

**Issue by gt7901b** [dtm2451/dittoSeq#58]
Hi, Daniel:

I installed the dittoSeq_1.0.2, but when I tried to run dittoDotPlot. I got the function not found error. Is it still in dev?

**Comment by gt7901b** [comment]
I figured it out.

**Comment by dtm2451** [comment]
Glad you could solve on your own! Adding the "solution" here though for anyone else who might be looking:

**Currently**, `dittoDotPlot()` is indeed devel versions only, v1.1.8 and up, and requires installation from Github, or the BioC-devel branch. (Ex: `BiocManager::install("dtm2451/dittoSeq")`.  Or for the best practices method, follow instructions [here](https://bioconductor.org/packages/devel/bioc/html/dittoSeq.html) but note that this method involves updating ALL BioC packages to their development versions.)

**Next month** (after the next Bioconductor release cycle at the end of October), it will be part of the release version of the package which comes with the typical `BiocManager::install("dittoSeq")`
