### ISSUE TITLE
color separation in multi_dittoDimPlotVaryCells

### ISSUE THREAD

**Issue by gt7901b** [dtm2451/dittoSeq#61]
Hi, Daniel:

I tried to plot logged clone size in my seurat object by patient. But the color seems always the default blue yellow ditto.colors, even when I set the color.panel = c("blue", "orange", "purple", "yellow", "red").
dittoSeq  treated logged clone size as discrete or continuous? Do I need to set the color levels?
can I do something like
scale_color_gradientn(colors=c("lightgrey","#2c7bb6","yellow","#d7191c"), values=rescale(c(-0.1, 0, lowerbound, upperbwound)), guide="colorbar", limits=c(-0.1, ub), name='CloneSize')?

thanks for your time

**Comment by dtm2451** [comment]
Hi there!

It sounds like your logged clone size is a numeric value, so you would want to use `min.color` and `max.color`.

Some details:
dittoSeq does not change numeric/continuous data into a discrete encoding, or vice verse. Rather, it utilizes a different scale type, with different sets of exposed inputs, based on which type of data.
- For numeric/continuous data (like yours here), the inputs are `min.color` and `max.color`, with a few others that can adjust say the `min` and `max` values.
- For discrete/groupings data, the main input is the `color.panel` one you reference.

**Comment by gt7901b** [comment]
got it. Thank you
