### ISSUE TITLE
labeling in dittoDimPlot overrides factor order during faceting

### ISSUE THREAD

**Issue by jdrnevich** [dtm2451/dittoSeq#65]
Hi Dan - I've been enjoying your package and putting it through it's paces. I came across a bug in an admittedly unusual situation. I was trying to both split.by and do.label = TRUE, and found that somehow adding in the label caused the original factor order of the split.by category to be ignored. An example using the data set in your vignette:

```
library(dittoSeq)
library(scRNAseq)
library(SingleCellExperiment)
library(Seurat)
# Download data
sce <- BaronPancreasData()
# Trim to only 5 of the cell types for simplicity of vignette
sce <- sce[,meta("label",sce) %in% c(
  "acinar", "beta", "gamma", "delta", "ductal")]
## -----------------------------------------------------------------------------
# Make Seurat and grab metadata
seurat <- CreateSeuratObject(counts(sce))
seurat <- AddMetaData(seurat, sce$label, col.name = "celltype")
seurat <- AddMetaData(seurat, sce$donor, col.name = "Sample")
seurat <- AddMetaData(seurat,
                      PercentageFeatureSet(seurat, pattern = "^MT"),
                      col.name = "percent.mt")
# Basic Seurat workflow (possibly outdated, but fine for this vignette)
seurat <- NormalizeData(seurat, verbose = FALSE)
seurat <- FindVariableFeatures(object = seurat, verbose = FALSE)
seurat <- ScaleData(object = seurat, verbose = FALSE)
seurat <- RunPCA(object = seurat, verbose = FALSE)
seurat <- RunTSNE(object = seurat)
seurat <- FindNeighbors(object = seurat, verbose = FALSE)
seurat <- FindClusters(object = seurat, verbose = FALSE)

#Make split plot
dittoDimPlot(seurat, "celltype", split.by = "Sample")
# Note GSM*57 is first and GSM*60 is last

#Change celltype and Sample to factors not in alphabetical order
seurat$celltype <- factor(seurat$celltype, levels = c("ductal","gamma","acinar","beta","delta"))
seurat$Sample <- factor(seurat$Sample, levels = c("GSM2230760", "GSM2230757","GSM2230759","GSM2230758"))

#Split plot again
dittoDimPlot(seurat, "celltype", split.by = "Sample")
#GSM*60 is now first plot, as it should be

#Now also add labels:
dittoDimPlot(seurat, "celltype", split.by = "Sample", do.label = TRUE)
#GSM*60 is back to being last, but celltype factor ordering is preserved

```

Not sure what is going on (ggplot2 is an admitted weak spot for me) but thought I would bring it to your attention. Thanks!

**Comment by dtm2451** [comment]
Ah, this may be a bug in the dataframe I create to hold locations of the labels after splitting -- that's manual unfortunately, not through ggplot. I'll look into this. Thanks for pointing it out!

**Comment by dtm2451** [comment]
Indeed.  I did not keep the `split.by`-groupings columns, in the label-locations data, as factors at all.  So then `ggplot` defaults back to alphabetical/numerical ordering because it notices that there is disagreement between the per-cell `split.by` data versus the per-group `split.by` data.

In the `split-label` branch, I've added code to retain factor levels which should fix the issue; it looks right for me with the example you give above. If you install from that branch with
`BiocManager::install("dtm2451/dittoSeq@split-label")`, then restart R, and then try with your data, could you confirm that the issue is fixed for you?

**Comment by jdrnevich** [comment]
Thanks, Dan for your prompt response! I am teaching a workshop tomorrow on 10X and I don't want to change anything just yet, but I will try in the next day or two.

**Comment by dtm2451** [comment]
No worries, but whenever you get a non-inconvenient chance, I'd appreciate it!

I've checked a bunch myself and am pretty sure it's good.  I just feel like there's no going back once something is pushed to BioC, even though that's not at all actually true, so I like to be double/triple/qraudruple -sure lol.

**Comment by jdrnevich** [comment]
I just tried it out and it works for me - thanks for the fix!
