### ISSUE TITLE
dittobarplot split.by

### ISSUE THREAD

**Issue by cstrlln** [dtm2451/dittoSeq#72]
Split.by is really helpful in the graph tools dittoSeq provides. Maybe I'm missing something, but noticed doesn't work with split.by.
Currently I use cells.use and generate multiple graphs, do you have a suggestion?
Thanks!

**Comment by dtm2451** [comment]
Hi there!  I don't have a great suggestion for you as it sounds like you are already doing, with `cells.use`, exactly what I would have suggested.

BUT, I did have extending `split.by` to functions that don't have it on my to-do list.  There's a few functions I want to aim for, and I won't be able to make much headway here until next week, unfortunately, but I'll start with dittoBarPlot when I can, and I'll let you know how to access the in-progress version!

**Comment by cstrlln** [comment]
that sounds great, thank you!

**Comment by dtm2451** [comment]
Barely tested so far, but seems to work... implemented for `dittoBarPlot()` in the `split-by` branch!  You can install and test it out for yourself with `BiocManager::install("dtm2451/dittoSeq@split-by")`.

**Comment by cstrlln** [comment]
thanks will give it a try!

**Comment by cstrlln** [comment]
btw it worked well.
Also, I was having the same problem as another recently posted issue about cluster colors differences between barplot and dimplot, but now seems to work fine if I assign the proper order on the levels.

Had one more question, is there a way to pass another color panel info to dimplot? I would like to keep capabilities like dimhex but for consistency with previous data would like to use the viridis palette. I know it works if I add e.g. scale_fill_viridis but messes up the legend. I know the point of dittoSeq is mantaining the color panel but was wondering in case there's a simple way.

Thanks!

**Comment by dtm2451** [comment]
Sorry for the late reply!  How does `scale_fill_viridis` mess up your legends?

There's no built in way for swapping out scales entirely...  just `color.panel` to give different discrete or `min.color`/`max.color` to give different continuous colors.  I suspect `min.color`/`max.color` are not enough to fully recapitulate viridis coloring, but maybe it'd be close enough?

If it's "just" the title you can give `scale_fill_viridis_c(name = "<title_here>")` to fix.  Most dittoSeq legend adjustments can mostly be applied within the scale call.  The only one that comes to mind which is made elsewhere (but this doesn't apply to the Hex plotters) is `guides(color = guide_legend(override.aes = list(size=legend.color.size)))` for increasing the size of legend keys.

**Comment by dtm2451** [comment]
Closing as I think this is fully addressed, but feel free to reopen.

`split.by` has been added to dittoBarPlot in Bioc-devel, which will become the release version later in May.
