### ISSUE TITLE
Is it possible to get separate graphs for each split.by of dittoDimPlot? 

### ISSUE THREAD

**Issue by akstks** [dtm2451/dittoSeq#74]
Hello and thanks for developing this great visualization package!

I had a few questions about faceting with split.by in dittoDimPlot. 

Take a look at this example:
![test](https://user-images.githubusercontent.com/80491255/110865154-72baa400-82c3-11eb-8ef9-1658d1477161.jpg)

I have split my data based on a metadata column, but since this column has 8 conditions, one spot remains empty in the 3x3 grid, which I would like to fill with another dimplot.

My questions are the following:
1) Is there a way to move the empty spot from the right of the grid to the left? I have already reordered the graphs the way I wanted them by changing the factors in the order I wanted them to appear.
2) I tried merging this plot and the one that I would like to add to it by using ggarrange or similar methods but I could not get them to align.  Is it even possible to align a single plot with a plot that is already on a grid? 
3) I was thinking that if I had each plot produced by the split.by argument as a single object, it would be much easier to make my own grid, but I cannot find a way to do so. Is it possible to do that? 
4) If not, I could make a separate plot for each of the 8 conditions, but I would miss the cool grey box with the legend. Is there an argument to put that grey legend box in a standard dittoDimPlot without using the split.by argument? For example I would prefer to have that as my title instead of using main = 'Title', especially if later they would be arranged in a grid with its own title. 

Sorry if these questions are trivial, I am still very new at this, and would like to utilize the package to its full extent!
I understand that the questions might be more ggplot2 based rather than dittoSeq, but I would like to hear your opinion.
Thanks in advance.

**Comment by dtm2451** [comment]
Definitely a dittoSeq Q over ggplot, so good you came here!  dittoSeq shuttles the list of plots through to `gridExtra::grid.arrange()` by default to produce the plot grid, but if you give `list.out = TRUE` then it will instead return the list of plots directly!

**Comment by akstks** [comment]
Thank you for the instant reply!

Now where would I pass this argument? I can't seem to get it to work, by adding it when I am creating the dimplot.

**Comment by dtm2451** [comment]
WHat are you giving?  Should go in the dittoDimPlot call with your other inputs like `dittoDimPlot(..., list.out =TRUE)`

**Comment by akstks** [comment]
`splitplot <- dittoDimPlot(data, var = 'annotations', split.by = 'metadata column', main = 'Title', list.out = TRUE) + NoLegend() + theme(text = element_text(face = 'bold'))` 

```
Error in dittoDimPlot(data, "annos", split.by = "Stage.Sex", main = "Clusters split by Stage & Sex",  : 
  unused argument (list.out = TRUE)
```

I am on dittoSeq v1.2.5 , BioConductor 3.12 and R 4.0.3 (I do get a warning when loading dittoSeq that it was built under R 4.0.4)
Is there a newer version I should install, or update R?

**Comment by dtm2451** [comment]
Oh sorry, confused myself in responding so fast =p... I was thinking of `multi_dittoDimPlot`.  For faceting, that actually is entirely through ggplot, and I'm not sure how you would do it.

**Comment by akstks** [comment]
It's fine, I will inevitably find a roundabout way to get what I am looking for :P ... Thank you for the fast replies!

Closing the issue.

**Comment by dtm2451** [comment]
But actually, there is a `multi_` function that's relevant here which does have the `list.out` functionality.  Try giving:
```
splitplot <- multi_dittoDimPlotVaryCells(data, var = 'annotations', vary.cells.meta = 'metadata column', main = 'Title', list.out = TRUE, theme = NoLegend() + theme(text = element_text(face = 'bold')))

**Comment by akstks** [comment]
Wow, that actually works, thanks! 

My roundabout way was subseting the original data into 8 separate objects,  1 for each condition: 

`Idents(data) <- 'metadata_column'`
`condition1 <- subset(data, idents = 'condition1')`
etc. 

And then run: 
`plot1 <- dittoDimPlot(condition1, var = 'annotations', split.by = 'metadata_column', main = NULL ) + NoLegend() + theme(text = element_text(face = 'bold'))`

Which would obviously give me only one plot since there is 1 condition in that column. Then I would grid them all together.
I am thinking of doing it that way still, because I really like the grey box above the umap that split.by gives :P 

Yours is definitely a time saver though and I will definitely use it in the future!

**Comment by dtm2451** [comment]
Wondeful!  One last bit though that would make this code simpler too: Check out the `cells.use` input (for all ditto Viz functions *except for* the VaryCells one that I pointed you to above). You shouldn't need to subset your `object` for most dittoSeq goals. Instead, you just give `cells.use = data$metadata_column=='condition1'` to achieve the same thing as your subsetting, though more efficiently as you don't subset every data slot of the object!
