### ISSUE TITLE
Choose assay for Seurat objects?

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/DittoSeq#8]
Is there any way we can specify the assay to pull data from? This matters for Seurat objects because integrated assays don't typically contain all genes, and SCT assay normalized counts often have noise regressed out that makes the counts dependent in some way on each other. 

Typically, the "RNA" assay is what is wanted, but it'd be nice to be able to specify this directly. I have not dug through the source code to see how the current assay is chosen, but I assume it just uses the default assay of the object?

**Comment by j-andrews7** [comment]
I guess one can always change the `assay` of the object itself using `DefaultAssay`, but that gets a bit annoying swapping back and forth.

**Comment by dtm2451** [comment]
You are correct that DittoSeq currently uses the default assay.

**Comment by dtm2451** [comment]
I think adding this option would require a new, Seurat-v3 specific, input for most viz functions + my gene extraction-related functions + dimensional reduction extraction functions.  It can be done, but would take time.

**Comment by j-andrews7** [comment]
Yeah, this is probably something best just left to the user then, frankly. Noting it in the docs may be a good idea, but I wouldn't make adding it a huge priority.

**Comment by dtm2451** [comment]
I'm glad you agree =p.
