### ISSUE TITLE
Order column names in dittoheatmap

### ISSUE THREAD

**Issue by rahulnutron** [dtm2451/dittoSeq#83]
Thanks for this useful package.
I have a question about heatmap column ordering.
I am using a seurat object where the cell type names as well as orig.ident (sample) names are not in order.
I wanted to order them as 
ct<-c("Epidermal cells", "Mesophyll cells", "Xylem cells" , "Phloem cells" ,"Companion cells", "Tracheary element")
orig.ident <- ('S4','S2')

I used a code (to  order cell type only as I dont know how to order both the cell types and samples simultaneously)

dittoHeatmap(s.integrated,genes = c('AT4G38130',	'AT5G63110'),
             annot.by = c( "CellType","orig.ident"),col_order=ct)

which run but nothing changed.

I will thankful if anyone can suggest me how to order both the cell types and samples.

Regards,
Rahul
![Rplot04](https://user-images.githubusercontent.com/18325626/120673749-bd4b5700-c493-11eb-943a-d55bec4abba8.png)

**Comment by dtm2451** [comment]
Hey @rahulnutron,

I see a couple problems that make sense to me for why your code did not seem to change what you wanted.  Fixing and doing it properly should be pretty easy =).

*Why your code did not do what you wanted:* the ordering input built into dittoHeatmap is `order.by`, not ~`col_order`~, and also although it takes in a couple different forms, the direct value-order you'd tried is not one of them.

The documentation for `order.by`:
> Single string, string vector, or numeric vector which sets how cells/samples (columns) will be ordered when cluster_cols = FALSE. Strings should be the name of a gene, or metadata slot, but can also be multiple such values in order of priority. Alternatively, can be a numeric vector which gives the column index order directly.

*My recommendation*: the easiest path for you will be the "string vector" method for `order.by`.  Ultimately, you will give `order.by = c( "CellType","orig.ident")` but you would set the value-ordering by turning those metadata, within your seurat object, into factors that internally hold their own ordering.  Based on the code you give above:

```
# Update the 'CellType' and 'orig.ident' metadata so that they know their own intended order
seurat_object$CellType <- factor(
    seurat_object$CellType,
    levels = c("Epidermal cells", "Mesophyll cells", "Xylem cells" , "Phloem cells" ,"Companion cells", "Tracheary element")
)
seurat_object$orig.ident <- factor(
    seurat_object$orig.ident,
    levels = c("S2_WT", "S4_WT)
)
### If you want to change "S2_WT" and "S4_WT" to "S2" and "S4", use this instead!
# seurat_object$orig.ident <- factor(
#     seurat_object$orig.ident,
#     levels = c("S2_WT", "S4_WT"),
#     labels = c("S2", "S4")
# )

# Make the heatmap
dittoHeatmap(s.integrated, genes = c('AT4G38130', 'AT5G63110'),
    annot.by = c( "CellType","orig.ident"), order.by = c( "CellType","orig.ident"))
```

**Comment by rahulnutron** [comment]
Dear Daniel,
Many thanks for quick reply!

It worked after a small modification, I need to remove the order.by = c( "CellType","orig.ident") argument. Otherwise it give me this error 

Error in .var_OR_get_meta_or_gene(order.by, object, assay, slot) : 
  'var' is not a metadata or gene nor equal in length to ncol('object')

I hope this removal of order.by is fine, as the data ordered internally.

Regards,
Rahul

![image](https://user-images.githubusercontent.com/18325626/120689565-8b8ebc00-c4a4-11eb-81b3-164a20434816.png)

**Comment by dtm2451** [comment]
I mean, it worked so 🤷 lol.  It seems your object has the cells ordered by orig.ident anyway, and the default for `order.by` is `annot.by[1]` when `annot.by` is filled in, so --> "CellType".

That said, your error when using `order.by = c( "CellType","orig.ident")` tells me that either there is a bug in dittoSeq or you are using a version from before this input was updated.  Can you tell me what version of dittoSeq you are running?

**Comment by rahulnutron** [comment]
Hi, 

Thanks for clarifying. The version I am using is "Package dittoSeq version 1.0.2"
I noticed something, that might be relevant here. That when there are more orign.ident samples (S1, S2, S3, S4 and S5) and I used annot.by = c( "CellType","orig.ident") instead of annot.by = c( "orig.ident","CellType"), the labels are ordered but columns colors are not ordered for orig.ident.

Regards,
Rahul

**Comment by dtm2451** [comment]
You are indeed using a version from before the `order.by` input was able to handle multiple metadata for ordering (and in which the numeric vector option did not work properly).

The behavior you mention when there are more orig.idents makes sense.  As I'd said before, order.by will by default get the first element of your `annot.by`.  Thus it is either ordering by "CellType" or by "orig.ident" in these two cases.  The appearance of ordering by both "CellType" and "orig.ident" before was only because the cells in the S2+S4 object were already ordered with S2 first and S4 after, and thus dittoHeatmap's ordering by "Celltype" was sufficient to achieve "both".

Your options are to upgrade to a current version of dittoSeq in which you can actually give both these metadata to `order.by`, OR manually order the cells in your object based on the second metadata before running `dittoHeatmap()`.

**Comment by rahulnutron** [comment]
Hi, 

I installed the latest version from github and it works as you suggested. 
Bioconductor says it has 1.4.1 version, but I am not sure why I got 1.0.2.

Thanks!

**Comment by dtm2451** [comment]
You probably have Bioconductor 3.11 versions of everything else then.  `BiocManager::version()` I think.  I can't actually guarantee compatibility if you're now mixing the Bioc3.13 version of dittoSeq with Bioc3.11 versions of other tooling, but AFAIK there are no issues!

Feel free to reopen if needed, but seems fixed to me =)
