### ISSUE TITLE
Error when running dittoHeatmap

### ISSUE THREAD

**Issue by HousLi** [dtm2451/dittoSeq#85]
Hello, 

 I was encountering some errors when running the following scripts:

dittoHeatmap(cells, genes = NULL, metas = names(ES.cells),
annot.by = "groups",
fontsize = 7,
cluster_cols = TRUE,
heatmap.colors = colors(50))

Here is the error message generated after,

Error in .which_data(assay, slot, object)[genes, cells.use] :
invalid or not-yet-implemented 'Matrix' subsetting

Can you help me figure this out?

Thanks!
Hous

**Comment by dtm2451** [comment]
Hmm, (sorry for the delay) what version of dittoSeq are you using?

I don't think you would see this error if you have a version of the dittoHeatmap function that does accept `metas`. Looking at the code, `genes = NULL` would indeed cause the `.which_data()` call to be skipped in the current version of the package.

**Comment by HousLi** [comment]
Hello! 

Thanks for helping out! 

I use dittoSeq_1.0.2.

**Comment by dtm2451** [comment]
Ah, yea, that version of dittoSeq doesn't handle metadata.  You'll need to upgrade for this.

Not sure if you'd want to upgrade all of your Bioconductor to version 3.12 or 3.13, but that's one option with `BiocManager::install(version = "3.13")`.

You can also just upgrade dittoSeq via this github with `BiocManager::install("dtm2451/dittoSeq")` to get the equivalent of the current dittoSeq v1.4.1 without needing to update as many other bits.

The former option is more "best practice" and would prevent `BiocManager::valid()` from complaining about packages being too new, but dittoSeq's interactions with other Bioconductor packages aren't very complicated so it should be fine to have it out of sync.
