### ISSUE TITLE
Drop unused factor levels in dittoHeatmap

### ISSUE THREAD

**Issue by j-andrews7** [dtm2451/dittoSeq#86]
Currently, using `cells.use` to limit to cells of certain factors of a metadata variable in `dittoHeatmap` doesn't drop unused factor levels from the resulting legend. Passing `drop_levels = TRUE` to pheatmap also does not resolve this.

**Comment by dtm2451** [comment]
Should be fixed in #96.  Explaination here https://github.com/dtm2451/dittoSeq/issues/95#issuecomment-911916390

Also, apologies that your `do.hover` PR has languished for so long!

**Comment by dtm2451** [comment]
The fix for this is now pushed through in both release and devel!
