### ISSUE TITLE
Renaming gene IDs into gene names in dittoHeatmap

### ISSUE THREAD

**Issue by rahulnutron** [dtm2451/dittoSeq#87]
Again thanks for this tool!

I am trying to change the gene IDs with gene names. Although it is possible by "labels_row=gene_names", however it seems that the gene IDs in the plot and replaced gene names are not in order (wrong gene names are assigned).
Is there any way (like easy "dittoseq" way) to do this?

Regards,
Rahul

my code
filter_c_S2S4 <- c('AT1G52560', 'AT5G02500', 'AT5G02490', 'AT3G09440', 'AT3G12580')
cls="Epidermal cells"
pg<-dittoHeatmap(s.integrated,genes = intersect(filter_c_S2S4,rownames(s.integrated)),annot.by = c( "orig.ident","CellType"),
                 order.by = c( "orig.ident","CellType"),assay = 'SCT',
                 cells.use = colnames(subset(s.integrated,ident=cls)))

gene_labels <- pg$tree_row$labels
gene_order <- pg$tree_row$order 

gene_labels_ord <- gene_labels[gene_order]

dicn <- read.csv('gene_ID_to_name.csv',header = T)
dicn_names<-dicn$Name
names(dicn_names)<-dicn$ID

gl <- c()
for (g in gene_labels_ord){
  gl<-append(gl,paste(dicn_names[g]))
}

dittoHeatmap(s.integrated,genes = intersect(filter_c_S2S4,rownames(s.integrated)),annot.by = c( "orig.ident","CellType"),
                 order.by = c( "orig.ident","CellType"),assay = 'SCT',
                 cells.use = colnames(subset(s.integrated,ident=cls)),labels_row= gl)

I also tried 
pg+scale_y_discrete(labels = dicn_names)

which also doesn't work

**Comment by dtm2451** [comment]
Hmmm might help to have an even simpler code example that I could follow along myself, i.e. without needing your `s.integrated` or `gene_ID_to_name.csv`.  But I think that your issue is that `labels_row` should be given labels in the pre-clustering order, not post-clustering.  Try giving them in the same order as your `genes`.

(For your ggplot code attempt, pheatmap doesn't output a pure ggplot object unfortunately so that wouldn't work.)

**Comment by dtm2451** [comment]
Assuming that this issue is resolved, but feel free to reopen if not!

**Comment by rahulnutron** [comment]
> Hmmm might help to have an even simpler code example that I could follow along myself, i.e. without needing your `s.integrated` or `gene_ID_to_name.csv`. But I think that your issue is that `labels_row` should be given labels in the pre-clustering order, not post-clustering. Try giving them in the same order as your `genes`.
> 
> (For your ggplot code attempt, pheatmap doesn't output a pure ggplot object unfortunately so that wouldn't work.)

Thanks for your reply! however the suggestion to give them in the same order also didn't worked. But I managed to do that using this code

rownames(data_avg@assays$RNA@data)<-paste0(dicn_names[rownames(data_avg@assays$RNA@data)])
dittoHeatmap(data_avg,treeheight_row = 0,annot.by = c( "CellType","Condition"),order.by = c( "CellType","Condition"))
